export const APP_ROUTES = {
    HOME: "home",
    MAP: "map",
    ABOUT_COMPANY: "about-company",
    ABOUT: "about",
    PROGRESS: "progress",
    FEATURES: "features",
    LAYOUTS: "layouts",
    GENPLANS: "genplans",
    VISUALIZATION: "visualizations",
    LOCATIONS: "locations",
    PROPERTIES: "properties",
    FAVORITES: "favorites",
    COMPARE: "compare",
    PROJECTS: "projects",
};
